export const qk = {
  me: ["auth", "me"],
  users: (params) => ["users", params || {}],
  user: (id) => ["user", id],
  userActivity: (id, params) => ["user-activity", id, params || {}],
  analyticsOverview: ["analytics", "overview"],
  analyticsGrowth: (range) => ["analytics", "growth", range],
  analyticsUsage: (range, feature) => ["analytics", "usage", range, feature || null],
  analyticsRevenue: (range) => ["analytics", "revenue", range],
  analyticsRevenueBreakdown: (range) => ["analytics", "revenue-breakdown", range],
  channels: (params) => ["channels", params || {}],
  channelsSummary: (minSubs) => ["channels-summary", minSubs],
  cloudCosts: (days) => ["cloud-costs", days],
  finance: (days) => ["finance", days],
  styles: (params) => ["styles", params || {}],
  templates: (params) => ["templates", params || {}],
  feedback: (params) => ["feedback", params || {}],
  audit: (params) => ["audit", params || {}],
  events: (params) => ["events", params || {}],
  errors: (params) => ["errors", params || {}],
  flags: ["feature-flags"],
  billing: ["billing-snapshot"],
  env: ["env-snapshot"],
  thumbnailRefs: (params) => ["thumbnail-refs", params || {}],
  thumbnailRefTopicClasses: ["thumbnail-refs", "topic-classes"],
};
